#!/usr/bin/python3
import sys, tokenize, re
fd = open(sys.argv[1], 'r')
tokens = tokenize.generate_tokens(fd.readline)

def get_tab_num(string):
	ret_tab = 0
	tab_temp = re.finditer(r'\t', string)
	for i in tab_temp:
		ret_tab = i.span()[-1]
	return ret_tab

funcs_list = []
append_flag = 0
for token in tokens:
	current_def_tab_num = 0
	if token.string == "def":
		current_def_tab_num = get_tab_num(token.line)
		append_flag = 1
		if token.line not in funcs_list:
			funcs_list.append(token.line)
			continue
	
	if append_flag == 1:
		current_tab = get_tab_num(token.line)
		if current_tab > current_def_tab_num:
			print(token.line)
			if token.line not in funcs_list:
				funcs_list.append(token.line)
		if current_tab == current_def_tab_num:
			append_flag = 0

fd.close()
print(*funcs_list)
